config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :users
  resources :articles do
  collection { post :import }
  end

  get 'aanmelden' => 'users#new'
  get "inloggen" => "sessions#new"

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

PAPIERTYPEN= ['coated', 'uncoated']
KLEUR= ['full color', 'zwart']
DUPLEX= ['yes', 'no']

validates_presence_of :name, :duplex, :media, :papiertype, :inslag_staand, :inslag_liggend, :kleur, :aantal_drukvel
validates_uniqueness_of :name


def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |article|
      csv << article.attributes.values_at(*column_names)
    end
  end
end

# Hier nog aanpassing doen ivm afvangen foutmelding bij validation errors. Hoe terug geven aan controller en instance variabele gebruiken voor afdrukken fouten op scherm
def self.import(file)
	import_attributes = ["name", "duplex", "media", "papiertype", "inslag_staand", "inslag_liggend", "kleur", "aantal_drukvel"]
	CSV.foreach(file.path, headers: true) do |row|
		article = find_by_id(row["id"]) || new
		article.attributes = (row.to_hash.slice(*import_attributes))
		article.save!
		end
	end


def self.search(search)
	  where("name LIKE ?", "%#{search}%") 
	end


end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true,
                  format: /\A\S+@\S+\z/,
                  uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



private

def require_signin
unless current_user
  redirect_to new_session_url, alert: "Eerst inloggen alstublieft!"
end
end

def current_user
@current_user ||= User.find(session[:user_id]) if session[:user_id]
end

helper_method :current_user

def current_user?(user)
  current_user == user
end

helper_method :current_user?

def require_admin
  unless current_user_admin?
    redirect_to root_url, alert: "Niet toegestaan!"
  end
end

def current_user_admin?
  current_user && current_user.admin?
end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_signin
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    # @articles = Article.order('name ASC').all
    # @articles = Article.all
    if params[:search]
      @articles = Article.search(params[:search]).order("name ASC")
    else
      @articles = Article.all.order("name ASC")
    end
    respond_to do |format|
      format.html
      format.xml
      format.csv { send_data @articles.to_csv }
    end
  end


  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Artikel is succesvol aangemaakt.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { flash.now[:alert] = "Er zijn fouten bij het aanmaken van het artikel!" 
        render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Artikel is succesvol aangepast.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { flash.now[:alert] = "Er zijn fouten bij het updaten van het artikel!"
        render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Artikel is succesvol verwijderd.' }
      format.json { head :no_content }
    end
  end

  def import
    if !params[:file].blank?
      begin
      Article.import(params[:file])
      redirect_to root_url, notice: "Artikelen zijn geimporteerd!."
      rescue
        redirect_to root_url, alert: "Foutief CSV bestandsformaat, of ontbrekende velden in CSV bestand."
      end
    else
    redirect_to articles_url, alert: 'Geen bestand geselecteerd voor upload.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :duplex, :media, :papiertype, :inslag_staand, :inslag_liggend, :kleur, :aantal_drukvel)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


def new
end


def create
  user = User.find_by(email: params[:email])
  if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    flash[:notice] = "Welkom terug, #{user.name}!"
    redirect_to root_url
  else
    flash.now[:alert] = "Ongeldige email/wachtwoord combinatie!"
    render :new
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, notice: "Je bent uitgelogd!"
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :require_signin
before_action :require_admin, only: [:new, :create]
before_action :require_correct_user, only: [:edit, :update, :destroy]

def index
	@users = User.all
end

def show
  @user = User.find(params[:id])
end

def new
	@user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    redirect_to users_path, notice: "Gebruiker aangemaakt!"
  else
    flash.now[:alert] = "Er zijn fouten bij het aanmaken van de gebruiker!"
    render :new
  end
end

def edit
end

def update
  if @user.update(user_params)
    redirect_to @user, notice: "Account succesvol opgeslagen!"
  else
    flash.now[:alert] = "Er zijn fouten bij het updaten van de gebruiker!"
    render :edit
  end
end

def destroy
  @user.destroy
  if current_user && current_user.admin?
    redirect_to users_path
    else
    session[:user_id] = nil
    redirect_to root_url, notice: "Account succesvol verwijderd!"
  end
end

private

def user_params
  params.require(:user).
    permit(:name, :email, :password, :password_confirmation)
end


  def require_correct_user
    @user = User.find(params[:id])
      redirect_to root_url, alert: "Niet toegestaan!" unless current_user?(@user) || current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
<%= render "shared/errors", object: @article %>

  <div class="field">
    <%= f.label :name, 'Naam' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :duplex %><br>
    <%= f.select :duplex, Article::DUPLEX %>
  </div>
  <div class="field">
    <%= f.label :media %><br>
    <%= f.text_field :media %>
  </div>
    <div class="field">
    <%= f.label :papiertype %>
    <%= f.select :papiertype, Article::PAPIERTYPEN %><br>
  </div>
  <div class="field">
    <%= f.label :inslag_staand %><br>
    <%= f.text_field :inslag_staand %>
  </div>
  <div class="field">
    <%= f.label :inslag_liggend %><br>
    <%= f.text_field :inslag_liggend %>
  </div>
  <div class="field">
    <%= f.label :kleur %><br>
    <%= f.select :kleur, Article::KLEUR %>
  </div>
  <div class="field">
    <%= f.label :aantal_drukvel %><br>
    <%= f.text_field :aantal_drukvel %>
  </div>

  <div class="actions" >
    <%= f.submit 'Bevestigen', :class=> 'whitetext' ' ' 'button tiny' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h2>Aanpassen SKU</h2>

<%= render 'form' %>

<%= link_to 'Weergeven', @article, :class=> 'whitetext' ' ' 'button tiny' %>
<%= link_to 'Terug', articles_path, :class=> 'whitetext' ' ' 'button tiny' %>

app/views/articles/index.html.erb
<h2>SKU overzicht HelloPrint</h2>

<nav>
  <ul style="list-style: none;">
<li class="button small"><%= link_to 'Nieuw artikel', new_article_path, :class=>("whitetext") %> </li>
<li class="button small"><%=link_to "Download XML", articles_path(format: "xml"), :class=>("whitetext") %></li>
<li class="button small"><%= link_to "Download CSV", articles_path(format: "csv"), :class=>("whitetext") %></li>
<li>
</nav>

<div>
<%= form_tag(articles_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Zoek artikelen" %>
<%= submit_tag "Zoeken" %>
<% end %>

<% if @articles.present? %>
<% else %>
  <p>Er zijn geen artikelen gevonden met de zoekterm(en) <%= params[:search] %>.</p>
<% end %>
<br>
</div>
<table>
  <thead>
    <tr>
      <th>Naam</th>
      <th>Duplex</th>
      <th>Media</th>
      <th>Papiertype</th>
      <th>Inslag staand</th>
      <th>Inslag liggend</th>
      <th>Kleur</th>
      <th>Aantal drukvel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.name, article %></td>
        <td><%= article.duplex %></td>
        <td><%= article.media %></td>
        <td><%= article.papiertype %></td>
        <td><%= article.inslag_staand %></td>
        <td><%= article.inslag_liggend %></td>
        <td><%= article.kleur %></td>
        <td><%= article.aantal_drukvel %></td>
        <td class="button tiny"><%= link_to 'Weergeven', article, :class=>("whitetext") %></td>
        <td class="button tiny"><%= link_to 'Aanpassen', edit_article_path(article),:class=>("whitetext") %></td>
        <td class="button tiny"><%= link_to 'Verwijderen', article, :class=>("whitetext"), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<nav>
  <ul style="list-style: none;">
<li class="button small"><%= link_to 'Nieuw artikel', new_article_path, :class=>("whitetext") %> </li>
<li class="button small"><%=link_to "Download XML", articles_path(format: "xml"), :class=>("whitetext") %></li>
<li class="button small"><%= link_to "Download CSV", articles_path(format: "csv"), :class=>("whitetext") %></li>
<li>

  <% if current_user && current_user.admin? %>
  <h3>Importeer CSV file</h3>
   
    <%= form_tag import_articles_path, multipart: true do %>
    <%= file_field_tag :file %> 
    <%= submit_tag "Import CSV", :class=> 'whitetext' ' ' 'button small' %>
    <% end %>
</li>
</ul>
<% end %>


</nav>



          

app/views/articles/new.html.erb
<h2>Nieuwe SKU invoeren</h2>

<%= render 'form' %>

<%= link_to 'Terug', articles_path, :class=> 'whitetext' ' ' 'button tiny' %>

app/views/articles/show.html.erb
<ul style="list-style: none;">
<li>
  <strong>Name:</strong>
  <%= @article.name %>
</li>

<li>
  <strong>Duplex:</strong>
  <%= @article.duplex %>
</li>

<li>
  <strong>Media:</strong>
  <%= @article.media %>
</li>

<li>
  <strong>Papiertype:</strong>
  <%= @article.papiertype %>
</li>

<li>
  <strong>Inslag staand:</strong>
  <%= @article.inslag_staand %>
</li>

<li>
  <strong>Inslag liggend:</strong>
  <%= @article.inslag_liggend %>
</li>

<li>
  <strong>Kleur:</strong>
  <%= @article.kleur %>
</li>

<li>
  <strong>Aantal drukvel:</strong>
  <%= @article.aantal_drukvel %>
</li>
</ul>

<%= link_to 'Aanpassen', edit_article_path(@article), :class=> 'whitetext' ' ' 'button tiny' %>
<%= link_to 'Terug', articles_path, :class=> 'whitetext' ' ' 'button tiny' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Hello Print SKU lookup" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <header>
      <nav>
        <p>
          <%= link_to "Home", root_url, class: 'button'  %>
          <% if current_user %>
            <%= link_to current_user.name, current_user, class: 'button'  %>
            <%= link_to "Account Instellingen", edit_user_path(current_user), class: 'button'  %>
            <%= link_to 'Uitloggen', session_path, method: :delete, class: 'button' %>
          <% end %>
            <% if current_user && current_user.admin? %>
            <%= link_to "Gebruikers instellingen", users_path, class: 'button'  %>
          <% end %>
        </p>
      </nav>
      </header>
      <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <%= content_tag :div, msg, class: "alert-box #{name} radius" %>
        <% end %>
      <% end %>
      <div class="small-12 large-12 columns">
            <%= yield %>
      </div>
    </div>  
    

  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.titleize.downcase %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/errors", object: @user %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :email %>
        <%= f.email_field :email, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password %>
        <%= f.password_field :password, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, size: 40 %>
      </li>
    </ol>
    <p>
      <% if @user.new_record? %>
        <%= f.submit "Account opslaan" %>
      <% else %>
        <%= f.submit "Account updaten" %>
      <% end %>
    </p>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<header id="content-header">
  <h1>Account aanpassen</h1>
</header>

<%= render 'form' %>

app/views/users/index.html.erb
<header id="content-header">
  <h1><%= pluralize(@users.size, 'User') %></h1>
</header>

<ul id="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<% if current_user && current_user.admin? %>
	<%= link_to "Nieuwe gebruiker", new_user_path, :class => 'button' %>
<% end %>

app/views/users/new.html.erb
<header id="content-header">
  <h1>Sign Up</h1>
</header>


<%= render 'form' %>

app/views/users/show.html.erb
<article id="user">
  <header>
    <h1><%= @user.name %></h1>
    <h2><%= mail_to(@user.email) %></h2>
  </header>
</article>
<footer>
  <nav>
    <% if current_user?(@user) || current_user.admin? %>
      <%= link_to 'Account aanpassen', edit_user_path(@user), class: 'button' %>
      <%= link_to 'Account verwijderen', @user,
              method: :delete,
              data: { confirm: 'Weet je zeker dat je dit account wilt verwijderen?' },
              class: 'button' %>
    <% end %>
  </nav>
</footer>